version: "3"

tasks:
  default:
    desc: Show all tasks
    cmds:
      - task --list-all
  deploy:
    desc: Deploy app to heroku
    cmds:
      - git push heroku master
  devback:
    desc: Start dev server
    cmds:
      - gunicorn mailtesttask.asgi:application -k uvicorn.workers.UvicornWorker
  devfront:
    desc: Start dev server for front
    cmds:
      - task devback &
      - npm start dev
