# Generated by Django 4.0.4 on 2022-05-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='book',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='recordkeeper.book'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='book',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='recordkeeper.book'),
        ),
    ]
