# Generated by Django 4.0.4 on 2022-05-19 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordbook',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
