# Generated by Django 4.0.4 on 2022-05-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordkeeper', '0002_alter_record_book_alter_shortlink_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
