# Generated by Django 4.0.4 on 2022-05-21 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordkeeper', '0003_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordkeeper.book'),
        ),
    ]
